config/routes.rb
Rails.application.routes.draw do
  resources :ribbits
  get 'sessions/new'

 post 'sessions/create'

  get 'sessions/destroy'

  resources :users
    root to: 'users#new'

end

app/models/ribbit.rb
class Ribbit < ActiveRecord::Base
     default_scope order: 'createdat DESC'
  attr_accessible :content, :userid
  belongs_to :user
 
  validates :content, length: { maximum: 200 }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :ribbits
    
    def attr_accesible
    attr_accessible :avatar_url, :email, :name, :password, :password_confirmation, :username
has_secure_password
        before_save :create_avatar_url
    before_validation :prep_email
validates :name, presence: true
validates :username, uniqueness: true, presence: true
            validates :email, uniqueness: true, presence: true
    validates :email, uniqueness: true, presence: true, format: { with: /^[\w.+-]+@([\w]+.)+\w+$/ }
    end

    private
def prep_email
    self.email = self.email.strip.downcase if self.email
end     
    def create_avatar_url
    self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    private
 
def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
 
helper_method :current_user
    
end

app/controllers/ribbits_controller.rb
class RibbitsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
       user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
        session[:userid] = user.id
        redirect_to rooturl, notice: "Logged in!"
    else
        flash[:error] = "Wrong Username or Password."
        redirect_to root_url
    end
  end

  def destroy
       session[:userid] = nil
    redirect_to root_url, notice: "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    @user = User.new
end
    def create
        @user = User.new(params[:id])
  if @user.save
      session[:user_id] = @user.id
    redirect_to @user, notice: "Thank you for signing up for Ribbit!"
  else
    render 'new'
  end
end
    
def show
    @user = User.find(params[:id])
    @ribbit = Ribbit.new
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ribbits_helper.rb
module RibbitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet/less" href="/style.less">
    <script src="/less.js"></script>
</head>
<body>
    <header>
                 <img src="/gfx/logo.png"><br>

        <div class="wrapper">

            <% if current_user %>
    <%= link_to "Log Out", sessions_destroy_path %>
<% else %>
    <%= form_tag sessions_create_path do %>
        <%= text_field_tag :username, nil, placeholder: "username" %>
        <%= password_field_tag :password, nil,  placeholder: "password" %>
        <%= submit_tag "Log In" %>
    <% end %>
<% end %>
        </div>
    </header>
    <div id="content">
        <div class="wrapper">
            <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, class: "flash #{name}" %>
            <% end %>
            <%= yield %>
        </div>
    </div>
    <footer>
        <div class="wrapper">
            Ribbit - A Twitter Clone Tutorial<img src="/gfx/logo-nettuts.png">
        </div>
    </footer>
</body>
</html>

app/views/users/new.html.erb
<img src="/gfx/frog.jpg">
 
<div class="panel right">
  <h1>New to Ribbit?</h1>
   
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
 
    <%= f.text_field :email, placeholder: "email" %>
    <%= f.text_field :username, placeholder: "username" %>
    <%= f.text_field :name, placeholder: "name" %>
    <%= f.password_field :password, placeholder: "password" %>
    <%= f.password_field :password_confirmation, placeholder: "password" %>
    <%= f.submit "Create Account" %>
  <% end %>
</div>

app/views/users/show.html.erb
<% if current_user %>
<div id="createRibbit" class="panel right">
    <h1>Create a Ribbit</h1>
    <p>
    <%= form_for @ribbit do |f| %>
        <%= f.textarea :content, class: 'ribbitText' %>
        <%= f.submit "Ribbit!" %>
    <% end %>
    </p>
</div>
<% end %>
<div id="ribbits" class="panel left">
    <h1>Your Ribbit Profile</h1>
    <div class="ribbitWrapper">
        <img class="avatar" src="<%= @user.avatar_url %>">
        <span class="name"><%= @user.name %></span> @<%= @user.username %>
        <p>
        <%= @user.ribbits.size %> Ribbits
        <span class="spacing">XX Followers</span>
        <span class="spacing">XX Following</span>
        </p>
    </div>
</div>
<div class="panel left">
    <h1>Your Ribbits</h1>
    <% @user.ribbits.each do |ribbit| %>
        <div class="ribbitWrapper">
            <img class="avatar" src="<%= @user.avatar_url %>">
            <span class="name"><%= @user.name %></span> 
            @<%= @user.username %> 
            <span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
            <p> <%= ribbit.content %> </p>
        </div>
    <% end %>
</div>